### ISSUE TITLE
Read is rather useless.

### ISSUE THREAD

**Issue by ericlagergren** [ammario/crand#2]
[Read](https://github.com/ammario/crand/blob/master/rand.go#L9) is useless because [crypto/rand.Read](https://golang.org/src/crypto/rand/rand.go?s=714:752#L11) does _exactly_ what you want.

Also, on _nix systems `rand.Read` reads from `/dev/urandom` which is non-blocking (although I do think Windows' CryptGenRandom *is_ blocking, but that's entirely irrelevant here) so your docs which state:

> Crand does not tolerate rand.Reader errors and will block until enough entropy is available.

Aren't exactly correct.

**Comment by ammario** [comment]
Thanks, removing that in next commit.

**Comment by ericlagergren** [comment]
No, it is _not_ safe to ignore the error.

**Comment by ammario** [comment]
From sifting through the crypto/rand code it seems that most errors have to do with obscure OS misconfiguration and it should be sufficient to provide something like a "LastError() error" func? I would like to avoid having  to return errors on the general API funcs.

**Comment by ericlagergren** [comment]
If your goal is a cryptographically-secure library then you need to return
errors, full stop. Anything less is unsafe and detrimental to people who
use the library.

If your goal is a wrapper around math/rand with convenience functions that
return int8s and strings then, no, you don't need to return errors. In
fact, if this is your objective I'd forego crypto/rand and just use
math/rand. It'll be much faster.

**Comment by ammario** [comment]
I suppose you're correct. I've returned errors with @ffcd42ec12a13af68de65f78d1e07f691f35e50f
